### ISSUE TITLE
Guide: Executive Summary should be listed as the first page in the guide  in the sidenav (before introduction)

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#36]
If keystone, Mariano feel free to remove yourself and assign johnny. 

This is a bit confusing perhaps, but introduction actually comes after executive summary. in the side nav, they are listed in the wrong order. when reading the guide itself, they appear in the correct order. Not sure if this is a template thing or keystone thing. 

![screen shot 2017-01-04 at 3 59 37 pm](https://cloud.githubusercontent.com/assets/10051544/21658907/5a4ad9c6-d296-11e6-938c-02d65d9e37e7.png)

**Comment by esalling23** [comment]
This (I think) is because the guide initially links to the Executive Summary page, even though the Introduction is listed as being first. I have updated the models to be drag-and-drop sortable in keystone, so the Introduction guide page can simply be dragged to be before the Executive Summary. (The "first" item would be at the bottom of the list in Keystone)

**Comment by jpailthorpe** [comment]
confirmed fix!
