### ISSUE TITLE
Gamepage: Images are cropped incorrectly and appearing as lower quality

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#41]
*Assigning both @johnnycrich and @MarianoMiguel because i am not sure if this is cloudinary/keystone thing or a front css thing.*

one idea that might be a quick fix is to change how these feature items respond when in mobile view. Maybe keeping the aspect ratio of the image and stacking it on top of the text field rather than stretching it to fit across and on top of the text? 

![screen shot 2017-01-05 at 1 10 38 pm](https://cloud.githubusercontent.com/assets/10051544/21691717/bc9bf20c-d347-11e6-8299-5ed51b907fcc.png)

Or, I am also cool with simply hiding the pictures when in mobile view if this is easier. 

![screen shot 2017-01-05 at 1 11 29 pm](https://cloud.githubusercontent.com/assets/10051544/21691731/c97f3a10-d347-11e6-8987-05174a30f39b.png)

**Comment by MarianoMiguel** [comment]
@jpailthorpe Working on this. Will probably have some news by tonight / tomorrow. I'm trying to find a way of scaling the images that works well w/ every device, and that can handle anything that we throw at it (we need to be able to re-use the component in other places)

**Comment by johnnycrich** [comment]
The case study images now use 'thumb' cropping to fix issue with image mis-sizing.

**Comment by MarianoMiguel** [comment]
@jpailthorpe Images are appearing as low quality because they are (we are pulling 200px width images from Cloudinary, so we probably should up that resolution a bit).

The problem with the scaling and warping in this case, is that there are so many factors to consider (content length, image aspect ratio, etc) that it becomes practically impossible to deliver a consistent content & image size for every card AND preserve the aspect ratio of those images across all devices. 

You could always let the image dictate how much space it takes inside the card based on its own aspect ratio, but you'll end up having some images taking up 75% of the card width in some cases, then 30% in other cases, some images wouldn't be able to take 100% of the card height either = inconsistency in design.

My solution to this has been to hardcode some parameters (like how wide or tall the image area should be), and then scale & crop the image to cover that area entirely. This preserves aspect ratio, but some areas of the image will naturally be cropped. 

My recommendation would be to follow the same approach as every other card in the UI: Using more "decorative" images that don't require the entire image to be visible in order to look good i.e: images w/o text.

**Comment by jpailthorpe** [comment]
@MarianoMiguel Thanks for the detailed update! I think this is detailed enough with soloid direction that we can take any edits on this subject across the site from here. I am going to unassign you but keep this open to remind myself to address it next week

**Comment by msuen** [comment]
@jpailthorpe Any updates on where you landed with this? I think Mariano's point is a good one, and that either high quality, ratio-friendly versions of the assets you're using or more decorative elements might just work better here.

**Comment by jpailthorpe** [comment]
@msuen will address either tomorrow or wednesday, but definitely taking that advice and running with it. will update when more info

**Comment by jpailthorpe** [comment]
I ended up disabling the images on the cards in the template. I just wanted to get a viewable site ready for review for Eric. We will return to this in the future, closing for now!
