### ISSUE TITLE
ActivityPage: Remove the "goal question"  in header of activity

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#75]
The way the model is setup seems to be pulling the header text from the question, which is also used for process builder. I simply would like there to be NO additional text in the header. Most likely just requires editing the template. Just make sure the text for the question does not get removed in the builder or grid cards. 

![qa cityaccelerator net-toolkit-builder](https://cloud.githubusercontent.com/assets/10051544/22043098/103fc3f0-dcdc-11e6-8aa1-0ddb365f4afc.png)

**Comment by esalling23** [comment]
@jpailthorpe no longer seeing this on that activity or any others! I think it was previously a content issue, since that text is pulling from the description, not the question, on the front-end (an activity's question was put down as its description, so the question showed up where the description should have)

**Comment by jpailthorpe** [comment]
fixed
