### ISSUE TITLE
GlobalHeader: Header sizing needs to shift in order to match mockup height+afford logo sizing

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#79]
I am pretty sure we just need to remove the padding here in the main css file for the main header div to get to be around 217px

```
 1536: .c-top-nav.c-top-nav + * {
 1537    padding-top: 90px;
 1538    padding-top: 5.625rem; }
```

and then change the nav wrapper from 5.625 to 8-9 to give at least a height of 150px for the nav wrap. 
 
```
 1540: .c-top-nav__wrapper {
 1541    height: 90px;
 1542    height: 5.625rem;
```

**Comment by msuen** [comment]
@MarianoMiguel Can you increase the height of the global header/hero, so that it's more in line with the mockup?

**Mockup**
<img width="1423" alt="screen shot 2017-01-20 at 3 59 11 pm" src="https://cloud.githubusercontent.com/assets/2809369/22165367/69db6294-df29-11e6-8414-c5f31c38b523.png">

**Staging**
<img width="1439" alt="screen shot 2017-01-20 at 3 59 42 pm" src="https://cloud.githubusercontent.com/assets/2809369/22165385/7c1e7db0-df29-11e6-8999-da7ff2a3bf31.png">

**Comment by jpailthorpe** [comment]
@msuen @MarianoMiguel if its not a pain, I would really appreciate it, since we are going to be integrating the per logo into the header.

**Comment by jpailthorpe** [comment]
reminder that Erica is going to tackle #70 tomorrow

**Comment by jpailthorpe** [comment]
we got this in :)
