### ISSUE TITLE
guide: Nav link titles sometimes are clunky/large, esp. on mobile screens. 

### ISSUE THREAD

**Issue by jpailthorpe** [engagementgamelab/city-accelerator-website#87]
I am not sure of a solution for this, but messing around we could just remove the title of each guide section: 

![qa cityaccelerator net-guide-executive-summary](https://cloud.githubusercontent.com/assets/10051544/22124336/6ff82b16-de5d-11e6-90fa-96957c12221a.png)

or the reverse, remove the next and back words and just use the arrows along with title: 

![qa cityaccelerator net-guide-executive-summary 1](https://cloud.githubusercontent.com/assets/10051544/22124466/f14d26b2-de5d-11e6-9b8d-52b825831d60.png)

**Comment by msuen** [comment]
They provide context, which is why I like them. They do look clunky, though. My feeling is because some of the nav titles get a little long. That, paired with long page titles, does get messy. Perhaps we can set a max width on both the page title and the nav titles, so anything beyond that breaks into a second line — that way, they don't bleed into one another.

On mobile, we can remove the titles entirely and just keep it as back/next. That will make the UI much clearer.

**Comment by jpailthorpe** [comment]
I think this was fixed somewhere between last week and friday. They now stack vertically, which is good enough for me! closing
