### ISSUE TITLE
Add gradients and drop shadows

### ISSUE THREAD

**Issue by msuen** [engagementgamelab/city-accelerator-website#92]
- Add box-shadow property of 0 7px 42px 0 rgba(0,0,0,0.23) to all buttons; increase all card box-shadow properties to same values
- Add linear gradients to all buttons. For turquoise: #00B5CB (bottom) to #62E2F2 (top); for blue: #24408E (bottom) to #36558E (top)

**Comment by jpailthorpe** [comment]
is this in? @msuen

**Comment by msuen** [comment]
I don't think @MarianoMiguel has seen this?

**Comment by jpailthorpe** [comment]
also note that we changed the table of content color on the guide to match the color of the guide. This was due to it being white, which blended into the page to the point of confusion and difficult for users (in two tests it took over a minute for one person to find the table of contents). The color change fixed this, however, since it shares the same class with the table of contents on the toolkit, it also has changed to the guide color. Its not the end of the world, but wanted to note this change.

**Comment by MarianoMiguel** [comment]
@jpailthorpe I think the most sensible thing to do here is to not modify the original table of content color, but to add a new variant of the component with the new color. That way we get to use (and re-use whenever needed) both the two variants wherever it makes sense

**Comment by MarianoMiguel** [comment]
@msuen @jpailthorpe The linear gradients would take a bit more to get in. Here's why: Since we needed the site's UI to be themable (e.g: easily switching color schemes in the toolkit builder), I opted for a more flexible approach that involves CSS variables.

The way it works, is that we have a couple color variables (--primary, --secondary, etc), and we change the content of those variables depending on the over-arching theme (.t-blue, .t-green, etc).

So, let's say we have a button and we need to theme it. Originally, we would have done something like:

```
button {
  background: black;
}

.t-red button {
  background: red;
}

.t-blue button {
  background: blue;
}

.t-red new-component {
  color: red;
}

.t-blue new-component {
  color: blue;
}
``` 

Now, what we do is just:

```
.t-blue {
  --primary: blue;
}

.t-red {
  --primary: red;
}

button {
  background: var(--primary);
}

.new-component {
 color: var(--primary);
}
```

That way, we can swap themes with just a class, and we get code that is a lot more maintainable since we don't need to add specific styles *for each possible theme for each component*.

The caveat of this method is that it becomes harder to treat each theme separately and change  details in one but not in all of them.

We could of course re-write how we handle buttons and mix up the approach a bit. So all I'm asking is if it's worth it maintenance-wise.

**Comment by jpailthorpe** [comment]
@MarianoMiguel not worth it to me, especially since there are very few buttons on the site in general. Thanks for the explanation though!!
